# Generated by Django 6.0.4 on 2026-04-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppCoder", "0002_entregable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entregable",
            name="entregado",
            field=models.BooleanField(default=False),
        ),
    ]
