# Generated by Django 6.0.4 on 2026-04-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppCoder", "0004_estudiante_profesor"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="modalidad",
            field=models.CharField(
                choices=[("ONL", "Online"), ("PRE", "Presencial"), ("HIB", "Hibrido")],
                default="PRE",
                max_length=3,
            ),
        ),
    ]
