# Generated by Django 6.0.4 on 2026-04-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppCoder", "0005_curso_modalidad"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="calificacion",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
