# Generated by Django 6.0.4 on 2026-04-28 11:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("AppCoder", "0006_curso_calificacion"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profesor",
            options={"verbose_name_plural": "Profesores"},
        ),
    ]
