# Generated by Django 6.0.4 on 2026-04-28 11:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("AppCoder", "0007_alter_profesor_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profesor",
            options={
                "ordering": ["-fecha_creacion"],
                "verbose_name": "Profesor",
                "verbose_name_plural": "Profesores",
            },
        ),
    ]
