# Generated by Django 6.0.4 on 2026-04-30 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppCoder", "0008_alter_profesor_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="camada",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1000000),
                ]
            ),
        ),
    ]
